### ISSUE TITLE
Split Failed

### ISSUE THREAD

**Issue by TechplexEngineer** [tweirtx/ReMatch#3]
Day One: https://www.twitch.tv/videos/396390430
Day Two: https://www.twitch.tv/videos/396547003
Day Three: https://www.twitch.tv/videos/396893195

Event: Southern NH District
Event Key: 2019nhsnh
https://www.thebluealliance.com/event/2019nhsnh

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/ReMatch/ReMatch/__main__.py", line 52, in <module>
    main_rewrite(args['event_key'], args['event_type'], args['video_id_day_one'], args['video_type_day_one'], args['video_id_day_two'], args['video_type_day_two'], args['video_id_day_three'], args['video_type_day_three'])
  File "/opt/ReMatch/ReMatch/__main__.py", line 33, in main_rewrite
    TBA.DB_setup(TBA(), event_key, day_one_timestamp, day_two_timestamp, day_three_timestamp, "frc")
  File "/opt/ReMatch/ReMatch/TBA.py", line 11, in DB_setup
    db = psycopg2.connect(dbname="rematch", user="rematch", password="matchbox").cursor()
  File "/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  Peer authentication failed for user "rematch"
```

I followed the directions in https://github.com/tweirtx/ReMatch/blob/master/POSIX_INSTALL.md to install ReMatch on an ubuntu 18.04 server

Thoughts?

**Comment by tweirtx** [comment]
That's interesting, I've never seen it before. I'll have to mess with some stuff later in a VM when I'm not busy with competition.

**Comment by noahhusby** [comment]
That error will appear if postgres isn't configured correctly. Try running install.sh again.

If the error persists, try running  `psql -U postgres -f setup.sql` or    `sudo -u postgres psql -f setup.sql`, from the ReMatch directory. This is responsible for configuring the SQL server.

**Comment by tweirtx** [comment]
Hey y'all,
Turns out my testing computers already had a line in the pg_hba.conf file that allowed this that isn't in there by default. I'm containerizing ReMatch to make this easier for everyone, and my Docker docs will be up shortly.

**Comment by tweirtx** [comment]
Docker guide is complete. The official solution is to use Docker, unless you feel like adding a rule for the rematch user to connect locally to pg_hba.conf
